# Generated by Django 4.2 on 2025-11-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='estado',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
