# Generated by Django 4.2 on 2025-10-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('material', 'Material'), ('herramienta', 'Herramienta'), ('equipamiento', 'Equipamiento')], max_length=50)),
                ('unidad', models.CharField(default='Unidad', max_length=50)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
