# Generated by Django 4.2 on 2025-10-17 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_beneficiario', models.CharField(max_length=255)),
                ('documento', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('fecha_avance', models.DateTimeField(auto_now_add=True)),
                ('gestion', models.ForeignKey(db_column='gestion_id', on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos_core.beneficiario', verbose_name='Beneficiario (gestion_id)')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['-fecha_avance'],
            },
        ),
    ]
