# Generated by Django 4.2 on 2025-10-29 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedores_app.proveedor'),
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='proveedores_app.proveedor'),
        ),
    ]
