# Generated by Django 4.2 on 2025-11-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos_app', '0001_initial'),
        ('inventario_app', '0002_producto_proveedor_alter_entradainventario_proveedor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='productos_app.producto'),
        ),
        migrations.AlterField(
            model_name='salidainventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='productos_app.producto'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
