# Generated by Django 4.2 on 2025-10-22 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Pago',
                'verbose_name_plural': 'Órdenes de Pago',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
