# Generated by Django 4.2 on 2025-10-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('contacto', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
