# Generated by Django 4.2 on 2025-10-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='rolModulo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actores', to='gestion_usuarios.rol', verbose_name='Rol / Módulo '),
        ),
    ]
