# Generated by Django 4.2 on 2025-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_alter_actor_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolmodulopermisos',
            name='modulo',
            field=models.CharField(choices=[('beneficiarios', '1 Beneficiarios'), ('inventario', '2 Inventario (Producción)'), ('proyectos', '3 Proyectos / Avance'), ('contabilidad', '4 Contabilidad'), ('auditoria', '5 Auditoría'), ('contratacion', '6 Contratación / Obra'), ('facturacion', '7 Facturación'), ('proveedores', '8 Proveedores'), ('usuarios', '9 Usuarios y Roles'), ('cartera', '10 Cartera'), ('nomina', '11 Nómina'), ('compras', '12 Compras'), ('operaciones_ti', '13 Operaciones TI / Docs'), ('tesoreria', '14 Tesorería')], max_length=50),
        ),
    ]
