# Generated by Django 4.2 on 2025-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0003_alter_rolmodulopermisos_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolmodulopermisos',
            name='permisos',
            field=models.CharField(default='V', max_length=10),
        ),
        migrations.AlterField(
            model_name='rolmodulopermisos',
            name='modulo',
            field=models.CharField(choices=[('beneficiarios', ' Beneficiarios'), ('inventario', ' Inventario (Producción)'), ('proyectos', ' Proyectos / Avance'), ('contabilidad', ' Contabilidad'), ('auditoria', ' Auditoría'), ('contratacion', ' Contratación / Obra'), ('facturacion', ' Facturación'), ('proveedores', ' Proveedores'), ('usuarios', ' Usuarios y Roles'), ('cartera', ' Cartera'), ('nomina', ' Nómina'), ('compras', ' Compras'), ('operaciones_ti', ' Operaciones TI / Docs'), ('tesoreria', ' Tesorería'), ('productos', 'Productos')], max_length=50),
        ),
    ]
